---
- name: create local database directory
  file:
    path: "{{ fetch_local_db_backup_dir }}"
    state: directory
  when: fetch_local_db_backup_dir is defined
  delegate_to: 127.0.0.1
- name: fetch database backup
  fetch:
    src: "{{ db_backup_path }}"
    dest: "{{ fetch_local_db_backup_dir }}/{{ db_backup_file }}"
    flat: yes
  when: fetch_local_db_backup_dir is defined
- name: create backup directory
  file:
    path: "{{ fetch_local_site_backup_dir }}"
    state: directory
  when: fetch_local_site_backup_dir is defined
  delegate_to: 127.0.0.1
- name: fetch site backup
  fetch:
    src: "{{ site_backup_path }}"
    dest: "{{ fetch_local_site_backup_dir }}/{{ site_backup_file }}"
    flat: yes
  when: fetch_local_site_backup_dir is defined
